### ISSUE TITLE
Can't download: 'Progress' has no attribute 'get_default_columns'

### ISSUE THREAD

**Issue by chris-aeviator** [geomagical/GeoSynth#2]
```
(geosynth) ➜  geosynth python -m geosynth download non-hdr --dst=./ --variant=demo
Traceback (most recent call last):
  File "/home/korny/micromamba/envs/geosynth/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/korny/micromamba/envs/geosynth/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/korny/micromamba/envs/geosynth/lib/python3.9/site-packages/geosynth/__main__.py", line 3, in <module>
    run_app(prog_name="geosynth")
  File "/home/korny/micromamba/envs/geosynth/lib/python3.9/site-packages/geosynth/cli/main.py", line 36, in run_app
    app(*args, **kwargs)
  File "/home/korny/micromamba/envs/geosynth/lib/python3.9/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/home/korny/micromamba/envs/geosynth/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/korny/micromamba/envs/geosynth/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/korny/micromamba/envs/geosynth/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/home/korny/micromamba/envs/geosynth/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/home/korny/micromamba/envs/geosynth/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/korny/micromamba/envs/geosynth/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/korny/micromamba/envs/geosynth/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/korny/micromamba/envs/geosynth/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/korny/micromamba/envs/geosynth/lib/python3.9/site-packages/geosynth/cli/download.py", line 32, in download
    *Progress.get_default_columns(),  # type: ignore[reportGeneralTypeIssues]
AttributeError: type object 'Progress' has no attribute 'get_default_columns'

```

**Comment by BrianPugh** [comment]
Sorry for the late response, turns out an insufficient lower bound was put on the dependency `rich`. We require at least version `v11.2.0`. This has been fixed in geosynth v1.0.1.
